export const BURGER_BUILDER_ADD_INGREDIENT = 'BURGER_BUILDER_ADD_INGREDIENT';
export const BURGER_BUILDER_REMOVE_INGREDIENT = 'BURGER_BUILDER_REMOVE_INGREDIENT';
export const BURGER_BUILDER_SET_INIT_DATA_INITIATE = 'BURGER_BUILDER_SET_INIT_DATA_INITIATE';
export const BURGER_BUILDER_SET_INIT_DATA = 'BURGER_BUILDER_SET_INIT_DATA';
export const BURGER_BUILDER_SET_INIT_DATA_FAILED = 'BURGER_BUILDER_SET_INIT_DATA_FAILED';

export const ORDERS_LOAD_ORDERS_INITIATE = 'ORDERS_LOAD_ORDERS_INITIATE';
export const ORDERS_LOAD_ORDERS = 'ORDERS_LOAD_ORDERS';

export const CHECKOUT_SEND_ORDER_INITIATE = 'CHECKOUT_SEND_ORDER_INITIATE';
export const CHECKOUT_SEND_ORDER_SUCCESS = 'CHECKOUT_SEND_ORDER_SUCCESS';
export const CHECKOUT_SEND_ORDER_FAIL = 'CHECKOUT_SEND_ORDER_FAIL';

export const INIT_PURCHASE = 'INIT_PURCHASE';

export const NOTICE = 'NOTICE';
export const NOTICE_END = 'NOTICE_END';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const REDIRECT = 'REDIRECT';
export const REDIRECT_END = 'REDIRECT_END';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOG_OUT_INITIATE = 'AUTH_LOG_OUT_INITIATE';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_TRY_AUTO_AUTH = 'AUTH_TRY_AUTO_AUTH';
export const AUTH_AUTO_AUTH_ATTEMPTED = 'AUTH_AUTO_AUTH_ATTEMPTED';
export const AUTH_SIGN_IN_INITIATE = 'AUTH_SIGN_IN_INITIATE';
export const AUTH_SIGN_UP_INITIATE = 'AUTH_SIGN_UP_INITIATE';